--- #YAML:1.0
name: CPAN-IndexPod
version: 0.24
author:
  - Leon Brocard <acme@astray.com>
abstract: Index the POD from an unpacked CPAN
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
