--- #YAML:1.0
name: CPAN-IndexPod
version: 0.22
author:
  - Leon Brocard <acme@astray.com>
abstract: Index the POD from an upacked CPAN
license: perl
requires:
  Class::Accessor::Chained: 0
  File::Find::Rule: 0
  Plucene::Simple: 0
  Pod::Simple: 0
  Test::More: 0
provides:
  CPAN::IndexPod:
    file: lib/CPAN/IndexPod.pm
    version: 0.22
generated_by: Module::Build version 0.23
